package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.46

import (
	"context"

	"github.com/arman-madi/go-hello-graphql/datasource"
	"github.com/arman-madi/go-hello-graphql/graph/model"
)

// Food is the resolver for the food field.
func (r *queryResolver) Food(ctx context.Context) ([]*model.Food, error) {
	return datasource.Foods(), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
