// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cuisine struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Food struct {
	ID         string        `json:"id"`
	Name       string        `json:"name"`
	Cuisine    *Cuisine      `json:"cuisine,omitempty"`
	Recipe     *string       `json:"recipe,omitempty"`
	Ingredient []*Ingredient `json:"ingredient"`
}

type Ingredient struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Query struct {
}
